//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblAbout
{
    public int AboutId { get; set; }
    public string AboutImage { get; set; }
    public string AboutImageDesc { get; set; }
    public string Image1 { get; set; }
    public string Image1Name { get; set; }
    public string Image1Desc { get; set; }
    public string Image2 { get; set; }
    public string Image2Name { get; set; }
    public string Image2Desc { get; set; }
    public string Image3 { get; set; }
    public string Image3Name { get; set; }
    public string Image3Desc { get; set; }
    public string Image4 { get; set; }
    public string image4Name { get; set; }
    public string Image4Desc { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<System.DateTime> ModfiedDate { get; set; }
    public Nullable<int> ModifiedBy { get; set; }
}
